### PR TITLE
Expand typing and general tidyup

### PR DESCRIPTION
**Pull request by Dreamsorcerer**

### CODE REVIEW

**Comment by Dreamsorcerer** [comment]
@webknjaz The codecov/patch check gives a 403 when I click for more details. Can we fix that, or disable the requirement?

**Comment by Dreamsorcerer** [comment]
@webknjaz Can we remove the requirement on codecov/patch? I think we should be able to make judgement calls on this.

**Comment by webknjaz** [comment]
@Dreamsorcerer maybe you could just lower the threshold yourself? https://docs.codecov.io/docs/codecov-yaml

**Comment by Dreamsorcerer** [comment]
Sure, I'll give that a go.

**Pull request merged**
