### PR TITLE
Deploy on git tag pushing

### PR DESCRIPTION
**Pull request by asvetlov**
@Dreamsorcerer you might be interested in this PR

Didn't check how it works, sorry

### CODE REVIEW

**Comment by Dreamsorcerer** [comment]
> @Dreamsorcerer you might be interested in this PR

Yep, especially if it means I don't have to figure out how to configure this. :P

**Comment by Dreamsorcerer** [comment]
@asvetlov Shall we merge and test this out?

**Comment by asvetlov** [comment]
Hey. 
Let me take the last look at PR, please.

**Comment by asvetlov** [comment]
Yes, I think the PR is ready.

@Dreamsorcerer do you want to make the next release?
If yes, do you need any help?

**Comment by Dreamsorcerer** [comment]
Yep, I'll run it past you tomorrow.

**Comment by asvetlov** [comment]
Sounds good.
Sorry, now I am busy with proxy loop implementation that could be very useful for testing asyncio programs: https://github.com/aio-libs/aioloop-proxy
It was on my to-do list for about 2.5 years :)
The overall design is done and TCP/UDP part is tested but I should write several dozens of tests still.

**Pull request merged**
