### PR TITLE
Add key_factory attr for redis_storage

### PR DESCRIPTION
**Pull request by smialy**
Fix for #28

### CODE REVIEW

**Comment by jettify** [comment]
I thinks it is good idea, could you please add test case with custom key factory?

**Comment by smialy** [comment]
Not problem.

**Comment by jettify** [comment]
Thanks! will merge tonight

**Comment by asvetlov** [comment]
@jettify please make a new release after merging

**Comment by jettify** [comment]
New version on pypi https://pypi.python.org/pypi/aiohttp_session/1.0.1

**Pull request merged**
