### PR TITLE
Test on Python up to 3.10

### PR DESCRIPTION
**Pull request by asvetlov**

### CODE REVIEW

**Comment by Dreamsorcerer** [comment]
Requires #616 to be completed.

**Comment by Dreamsorcerer** [comment]
We need aiomcache to be updated to have aiohttp-session working on 3.10+.

Seems the repo has been untouched for 4 years though. I made a start on some fixes at: https://github.com/aio-libs/aiomcache/pull/207
Although, this seems to be one of the repos I don't have maintainer access to.

**Comment by asvetlov** [comment]
@Dreamsorcerer added you as `aiomcache` maintainer.

I'll try to find time for review tomorrow.
Have too many things that require my attention, sorry.

**Comment by Dreamsorcerer** [comment]
Now blocked on #663. Hopefully will be good after that.

**Pull request merged**
